##核密度图：在现有的图形上，利用已有的数据，预估它的概率密度，无参概率密度。
par(mfrow=c(2,1))
d<-density(mtcars$mpg)
plot(d)
plot(d,main="Kernel Density of Miles Per Gallon")
polygon(d,col="red",border="blue")
rug(mtcars$mpg,col="brown")
##利用sm包
install.packages("sm")
library(sm) 
par(lwd=2)
attach(mtcars)
cyl.f<-factor(cyl,levels=c(4,6,8))
labels=c("4 cylinder","6 cylinder","8 cylinder")
sm.density.compare(mpg,cyl,xlab="Miles Per Gallon")
title(main="PG Distribution by Car Cylinders")
colfill<-c(2:(1+length(levels(cyl.f)
length(locator(1),levels(cyl.f),fill=colfill)
detach(mtcars)
